### ISSUE TITLE
Upgrade instructions refers to non-existing "service" command

### ISSUE THREAD

**Issue by bluikko** [percona/psmysql-docs#192]
Both the DEB and RPM upgrade using repo document at `blob/8.0/docs/upgrading-using-percona-repos.md` has a note that says:
> invoke the above command with **systemctl** instead of **service**

But the "above command" does not have any `service` in it at all:
> Stop the server with /etc/init.d/mysql stop.

The note should refer to something else than "service", for example: "[...] with **systemctl stop mysql** instead of **/etc/init.d/mysql stop**".

**Comment by alina-derkach-oaza** [comment]
Hi bluikko, the reported issues are already fixed in https://github.com/percona/psmysql-docs/pull/149. We will merge the PR soon. Thank you!
