### ISSUE TITLE
Percona XtraDB Cluster Quick start guide is not found

### ISSUE THREAD

**Issue by k1ng440** [percona/psmysql-docs#215]
Link to [Percona XtraDB Cluster Quick start guide](https://docs.percona.com/percona-xtradb-cluster/8.0/overview.html) is invalid from [Quickstart guide for Percona Server for MySQL](https://docs.percona.com/percona-server/8.0/quickstart-overview.html#for-high-availability) page.

**Comment by patrickbirch** [comment]
Fixing it. Thanks.
