### ISSUE TITLE
Document symbols are written incorrectly

### ISSUE THREAD

**Issue by KAiTO2928** [percona/psmysql-docs#260]
In the [address](https://docs.percona.com/percona-server/8.0/user-stats.html#information_schematable_statistics)
The example sql was written incorrectly and was originally written as 
_SELECT * FROM INFORMATION_SCHEMA.TABLE_STATISTICS WHERE TABLE_NAME=``tables_priv``;_  
Should read 
_SELECT * FROM INFORMATION_SCHEMA.TABLE_STATISTICS WHERE TABLE_NAME='tables_priv';_  
The symbols are wrong.

**Comment by patrickbirch** [comment]
Thanks. Will be fixed.
