### ISSUE TITLE
Percona Server install instructions lack additional prerequisite step

### ISSUE THREAD

**Issue by leewp14-inf** [percona/psmysql-docs#352]
Hi Percona team, 

I'm referring to the install instructions over here: https://docs.percona.com/percona-server/8.0/yum-repo.html#install

It does not mention the required step to disable mysql module beforehand, which is required to proceed the installation. Without doing so, the package percona-server-server can't be listed or installed by yum/dnf. 

In contrast, a tip to disable the mysql module is being mentioned at this percona blog post: https://www.percona.com/blog/rhel-8-packages-available-for-percona-products/

I did very much want to open a PR, but I'm not certain if this is a norm for RHEL users nor this is something applicable to certain situations only. I consider myself new to RHEL distributions. 

Thanks and have a great day!

**Comment by patrickbirch** [comment]
Thank you for your comment, but that is discussed 
https://docs.percona.com/percona-server/innovation-release/yum-download-rpm.html

An EL8-based RHEL distribution or derivatives package installation requires the mysql module to be disabled before installing the packages:

$ sudo yum module disable mysql
