### ISSUE TITLE
` instead of '

### ISSUE THREAD

**Issue by Zuko** [percona/psmysql-docs#361]
I wasted too much time on this. Please fix.

https://github.com/percona/psmysql-docs/blob/0afc05d41f6e52c53ae22c04e531fb382859c53e/docs/ldap-authentication.md?plain=1#L127

**Comment by alina-derkach-oaza** [comment]
Hi Zuko, thank you for reporting this issue. We'll fix it with https://github.com/percona/psmysql-docs/pull/371 and https://github.com/percona/psmysql-docs/pull/372
